Add a code of conduct
breizhcamp/website-legacy pull request #73
Opened 2023-04-22 17:17 UTC by nledez

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +Notre Code of conduct est simple, nous comptons sur le côté bienveillant et le bon sens de nos participants, speakers et sponsors pour ne pas entacher cette belle fête annuelle qu’est le BreizhCamp d
```suggestion
Notre Code of conduct est simple, nous comptons sur le côté bienveillant et le bon sens de nos participants, speakers et sponsors pour ne pas entacher d’un dérapage inapproprié cette belle fête annuelle qu’est le BreizhCamp . Si jamais vous étiez témoin d’un tel comportement lors de votre participation au BreizhCamp, n’hésitez pas à nous en faire part rapidement (on est facilement repérables, on est ceux qui courent dans tous les sens tout le temps).
```

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +* Tu seras gentil et gentille ; courtoise et courtois avec les gens que tu côtoieras sur place, quels que soient leur âge, leur couleur de peau, leur genre et leur langage de programmation profession
```suggestion
* Tu seras gentil et gentille ; courtoise et courtois avec les gens que tu côtoieras sur place, quels que soient leur âge, leur couleur de peau, leur genre, leur langage de programmation favori ou toute autre différence ;
```

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +* Tu accorderas de l’attention aux conférences, par respect pour l’orateur ou oratrice que tu es venu ou venue écouter ;
```suggestion
* Tu accorderas de l’attention aux conférences, par respect pour l’orateur ou oratrice ;
```

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +* Tu t’accommoderas sans rechigner de l’idée de ne pas disposer d’un accès internet pendant plus de vingt minutes (voir plus si affinités). Et tout le long de la conférence ;
```suggestion
* Tu t’accommoderas sans rechigner de l’idée de ne pas disposer d’un accès Internet pendant plus de vingt minutes (voir plus si affinités). Et tout le long de la conférence ;
```

Je ne comprends pas la fin de cette phrase.

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +* Tu partageras ton expérience avec tous ceux et celles qui n’ont pas eu de billet via les réseaux sociaux, c’est la meilleure pub qu’on puisse espérer.
```suggestion
* Tu partageras ton expérience via les réseaux sociaux, avec tous ceux et celles qui n’ont pas eu de billet, c’est la meilleure pub qu’on puisse espérer.
```

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +Le non-respect de ces règles de bienséance pourra entraîner l’exclusion de l’événement, à la seule discrétion d’un·e ou plusieurs organisateur·trices, ou de l’association.
```suggestion
Le non-respect de ces règles de bienséance pourra entraîner l’exclusion de l’événement, à la seule discrétion des membres de l'équipe d'organisation.
```

2023-04-22 18:23 UTC, PascalLeMerrer commented on content/code-of-conduct/_index.md
> +Si vous êtes harcelé ou harcelée ou victime de discrimination, ou si vous êtes témoin de harcèlement ou de discrimination à l’égard d’autres participant et/ou participantes, ou si vous craignez la su
```suggestion
* Si vous êtes harcelé ou harcelée ou victime de discrimination, 
* ou si vous êtes témoin de harcèlement ou de discrimination à l’égard d’autres participants ou participantes, 
* ou si vous craignez la survenue d’un incident,

contactez sans attendre un membre de l'équipe du Breizhcamp.
```

2023-04-22 20:24 UTC, nledez commented on content/code-of-conduct/_index.md
> +Notre Code of conduct est simple, nous comptons sur le côté bienveillant et le bon sens de nos participants, speakers et sponsors pour ne pas entacher cette belle fête annuelle qu’est le BreizhCamp d
Marrant. Je venais de faire la même reformulation :)

2023-04-24 12:52 UTC, lucsorel requested changes

2023-04-24 12:52 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +* harcelé ou harcelée ou victime de discrimination
```suggestion
* êtes victime de discrimination ou de harcèlement
```

2023-04-24 12:52 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +* êtes témoin de harcèlement ou de discrimination à l’égard d’autres participant et/ou participantes
```suggestion
* êtes témoin de harcèlement ou de discrimination à l’égard d’autres personnes
```

2023-04-24 12:52 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +Si vous êtes :
```suggestion
Contactez sans attendre un membre de l'équipe du Breizhcamp si vous :
```

2023-04-24 12:52 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +Contactez sans attendre un membre de l'équipe du Breizhcamp.
```suggestion
```

2023-04-24 12:52 UTC, lucsorel commented on content/conference/_index.md
> -
Peut-être pointer le code de bonne conduite depuis cette page quand même ?

2023-04-24 12:58 UTC, nledez commented on content/conference/_index.md
> -
C'est en gros en haut. Mais je regarde ça quand même

2023-04-24 13:24 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +* Tu n’oublieras pas ton parapluie (pour la crème solaire, les clichés bretons ont la vie dure, on va pas essayer de te la faire amener…) ;
```suggestion
* Tu n’oublieras pas ton parapluie (pour la crème solaire, les clichés bretons ont la vie dure, on ne va pas essayer de te la faire amener…) ;
```

2023-04-24 13:24 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +Les 10 commandements adressés aux humains participants au BreizhCamp :
```suggestion
Les commandements adressés aux personnes participant au BreizhCamp :
```

2023-04-24 13:24 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +* Tu ne trolleras pas excessivement ton prochain, même pour rire ;
```suggestion
```

2023-04-24 13:24 UTC, lucsorel commented on content/code-de-bonne-conduite/_index.md
> +* Tu ne trolleras pas excessivement ton prochain, même pour rire ;
c'est redondant avec le 1er commandement et le suivant

2023-04-24 13:24 UTC, lucsorel commented on content/conference/_index.md
> +[C'est par là](/code-de-bonne-conduite/)
```suggestion
[C'est par là](/code-de-bonne-conduite/).
```

2023-04-24 14:12 UTC, merged